#!/usr/bin/env python
"""Regenerates theme/static/css/pygments.css.

Pelican's Markdown reader highlights fenced code blocks (```prolog, ```sh,
```erlang, ...) with Pygments, but only emits `<span class="...">` markup —
it never ships a stylesheet for those classes. Without one, every fenced
code block on the site renders as unstyled black-on-white text regardless
of the language tag. This writes one stylesheet covering both color
schemes: the `friendly` style for light mode, and `gruvbox-dark` wrapped in
`@media (prefers-color-scheme: dark)` for dark mode, matching how Pico CSS
itself (loaded in theme/templates/base.html) auto-switches by OS
preference with no theme-toggle JS involved.

Run after changing either style name below:

    pipenv run python scripts/gen_pygments_css.py
"""

from pathlib import Path

from pygments.formatters import HtmlFormatter

LIGHT_STYLE = "friendly"
DARK_STYLE = "gruvbox-dark"
OUT_PATH = Path(__file__).parent.parent / "theme" / "static" / "css" / "pygments.css"


def main() -> None:
    light = HtmlFormatter(style=LIGHT_STYLE).get_style_defs(".highlight")
    dark = HtmlFormatter(style=DARK_STYLE).get_style_defs(".highlight")

    lines = [
        "/* Generated by scripts/gen_pygments_css.py — do not hand-edit. */",
        "",
        light,
        "",
        "@media (prefers-color-scheme: dark) {",
    ]
    lines += [f"  {line}" for line in dark.splitlines()]
    lines.append("}")
    lines.append("")

    OUT_PATH.write_text("\n".join(lines))
    print(f"wrote {OUT_PATH}")


if __name__ == "__main__":
    main()
